@baseUrl = "http//localhost:3000"

### Read all users
GET {{baseUrl}}/users

###login admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###login user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "maxime",
    "password": "admin"
}

### register a user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username": "maxime",
    "password": "bonjour"
}


### test
GET {{baseUrl}}/username/1