@baseUrl = http://localhost:3000

### Read all users
GET {{baseUrl}}/users

###login admin
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###login user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username": "maxime",
    "password": "admin"
}

### register a user
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
    "username": "maxime",
    "password": "bonjour"
}

### update reflexeGame score
PUT {{baseUrl}}/userScores/scoreReflexe
Content-Type: application/json

{
    "username": "admin",
    "scoreReflexe": 300
}

### update fast click score
PUT {{baseUrl}}/userScores/scoreFastClick
Content-Type: application/json

{
    "username": "admin",
    "scoreFastClick": 199
}

### update fast click score
PUT {{baseUrl}}/userScores/scoreFastClick
Content-Type: application/json

{
    "username": "admin",
    "scoreFastClick": 100
}
